//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entities.HRM
{


    public class Common_Gender
    {


        public int GenderID { get; set; }
        public string GenderName { get; set; }
        public string GenderNameBan { get; set; }
        public bool IsActive { get; set; }


    }
}
