//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entities.HRM
{
    
    public  class Common_EmploymentCategory
    {
    
        public int EmpCategoryID { get; set; }
        public string EmpCategoryName { get; set; }
        public string EmpCategoryNameBan { get; set; }
        public bool IsActive { get; set; }
    
      
    }
}
