//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entities.HRM
{

    public class Common_EmploymentType
    {
        public int EmpTypeID { get; set; }
        public string EmpTypeName { get; set; }
        public string EmpTypeNameBan { get; set; }
        public bool IsActive { get; set; }

    }
}
